baseURL = "http://www.example.com"
title = "xuanjin"
# theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
enableEmoji = true
# Enable Disqus comments
disqusShortname = "yourdiscussshortname"

[markup.highlight]
noClasses = true

[params]
author = "Xuan Jin"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Xuan Jin's personal website"
keywords = "blog,developer,personal"
info = ["Full Stack DevOps", "Magician"]
avatarURL = "images/2.jpg"
# gravatar = "john.doe@example.com"
dateFormat = "January 2, 2006"
since = 2023
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "dark"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = true
# Series see also post count
maxSeeAlsoItems = 8
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
# siteID = "ABCDE"
# serverURL = "analytics.example.com" # Default value is cdn.usefathom.com, overwrite this if you are self-hosting

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# serverURL = "analytics.example.com" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
# outboundLinksTracking = true
# fileDownloadsTracking = true

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]
# code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# siteID = "ABCDE" # Default value is "1", overwrite this if you are cloud-hosting
# serverURL = "analytics.example.com" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
# [params.googleTagManager]
# id = "gid"

# If you want to use Yandex Metrika(https://metrika.yandex.ru) for analytics, add this section
# [params.yandexMetrika]
# id = "gid"

# If you want to use Application Insights(https://azure.com/) for analytics, add this section
# [params.applicationInsights]
# connectionString = "connectionString"

# If you want to use microanalytics.io for analytics, add this section
# [params.microAnalytics]
# id = "ABCDE"
# dnt = "false" # respect DNT tracker, "true" by default

# If you want to use Pirsch(https://pirsch.io) for analytics, add this section
# [params.pirsch]
# code = "ABCDE"

# If you want to implement a Content-Security-Policy, add this section
# [params.csp]
# childsrc = ["'self'"]
# fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
# formaction = ["'self'"]
# framesrc = ["'self'", "https://www.youtube.com"]
# imgsrc = ["'self'"]
# objectsrc = ["'none'"]
# stylesrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://fonts.googleapis.com/",
#   "https://cdn.jsdelivr.net/",
# ]
# scriptsrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://www.google-analytics.com",
#   "https://cdn.jsdelivr.net/",
# ]
# prefetchsrc = ["'self'"]
# # connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
# connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"
project = "projects"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/xuanjin001"

# [[params.social]]
# name = "Gitlab"
# icon = "fa fa-2x fa-gitlab"
# weight = 2
# url = "https://gitlab.com/johndoe/"

# [[params.social]]
# name = "Twitter"
# icon = "fa fa-2x fa-twitter"
# weight = 3
# url = "https://twitter.com/johndoe/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/xuan-jin-awesomeness/"

# [[params.social]]
# name = "Medium"
# icon = "fa fa-2x fa-medium"
# weight = 5
# url = "https://medium.com/@johndoe"

# [[params.social]]
# name = "RSS"
# icon = "fa fa-2x fa-rss"
# weight = 6
# url = "https://myhugosite.com/index.xml"
# rel = "alternate"
# type = "application/rss+xml"

[[params.social]]
name = "Wordpress"
icon = "fa fa-2x fa-wordpress"
weight = 7
url = "https://xjin2.wordpress.com/"

[languages.en]
languageName = ":us:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

# [[languages.en.menu.main]]
# name = "Tags"
# weight = 3
# url = "tags/"

# [[languages.en.menu.main]]
# name = "Project List"
# weight = 2
# url = "projects/"
# # url = "categories/projects/"

[[languages.en.menu.main]]
name = "Projects"
weight = 5
url = "projects/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 6
url = "contact/"

# everything below is Chinese

# [languages.cn-ch]
# languageName = "🇨🇳"
# title = "金萱"

# [languages.cn-ch.params]
# author = "金萱"
# info = "全栈工程师"
# description = "全栈工程师"
# keywords = "blog,desenvolvedor,pessoal"

# [[languages.cn-ch.menu.main]]
# name = "About｜关于我"
# weight = 1
# url = "about/"

# [[languages.cn-ch.menu.main]]
# name = "Blog｜博客"
# weight = 2
# url = "posts/"

# [[languages.cn-ch.menu.main]]
# name = "Projects｜项目"
# weight = 3
# url = "projects/"

# [[languages.cn-ch.menu.main]]
# name = "Contact｜联系"
# weight = 5
# url = "contact/"

# below are from template, keep as a reference 

# [languages.pt-br]
# languageName = ":brazil:"
# title = "João Ninguém"

# [languages.pt-br.params]
# author = "João Ninguém"
# info = "Full Stack DevOps e Mágico"
# description = "Sítio pessoal de João Ninguém"
# keywords = "blog,desenvolvedor,pessoal"

# [[languages.pt-br.menu.main]]
# name = "About"
# weight = 1
# url = "about/"

# [[languages.pt-br.menu.main]]
# name = "Blog"
# weight = 2
# url = "posts/"

# [[languages.pt-br.menu.main]]
# name = "Projects"
# weight = 3
# url = "projects/"

# [[languages.pt-br.menu.main]]
# name = "Contact"
# weight = 5
# url = "contact/"
